"""fix unique contsraints for complex_id in news, galleries, documents

Revision ID: 0780a5a36f6c
Revises: 74d390042f99
Create Date: 2025-06-18 13:09:20.487119

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "0780a5a36f6c"
down_revision = "74d390042f99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_complexes_gallery_complex_id"), "complexes_gallery", type_="unique"
    )
    op.drop_constraint(op.f("uq_documents_complex_id"), "documents", type_="unique")
    op.drop_constraint(op.f("uq_news_complex_id"), "news", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_news_complex_id"), "news", ["complex_id"])
    op.create_unique_constraint(
        op.f("uq_documents_complex_id"), "documents", ["complex_id"]
    )
    op.create_unique_constraint(
        op.f("uq_complexes_gallery_complex_id"), "complexes_gallery", ["complex_id"]
    )
    # ### end Alembic commands ###
