"""add to complex requests

Revision ID: 123232cefddd
Revises: a13c08b2fa71
Create Date: 2025-07-16 11:13:47.314308

"""

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = "123232cefddd"
down_revision = "a13c08b2fa71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "add_to_complex_requests",
        sa.Column(
            "apartment_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "floor_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "riser_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_add_to_complex_requests_apartment_id_apartments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["floors.id"],
            name=op.f("fk_add_to_complex_requests_floor_id_floors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["riser_id"],
            ["risers.id"],
            name=op.f("fk_add_to_complex_requests_riser_id_risers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_add_to_complex_requests")),
        sa.UniqueConstraint(
            "apartment_id", "floor_id", "riser_id", name="uq_apartment_floor_riser"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("add_to_complex_requests")
    # ### end Alembic commands ###
