"""change precision for apartment

Revision ID: 22355b49b311
Revises: d68322991b1a
Create Date: 2025-07-29 15:35:27.770491

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22355b49b311"
down_revision = "d68322991b1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartments",
        "area",
        existing_type=sa.NUMERIC(precision=10, scale=1),
        type_=sa.Numeric(precision=5, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartments",
        "area",
        existing_type=sa.Numeric(precision=5, scale=1),
        type_=sa.NUMERIC(precision=10, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
