"""announcement remove redundant fields

Revision ID: 3cae8040645d
Revises: b27f8a0096bd
Create Date: 2025-07-23 15:14:00.024885

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cae8040645d"
down_revision = "b27f8a0096bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "is_highlighted")
    op.drop_column("promotions", "is_boosted")
    op.drop_column("promotions", "is_big_advert")
    op.drop_column("promotions", "is_phrase_added")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions",
        sa.Column("is_phrase_added", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "promotions",
        sa.Column("is_big_advert", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "promotions",
        sa.Column("is_boosted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "promotions",
        sa.Column("is_highlighted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
