"""remove is_approved field for announcement

Revision ID: 660b06b9ef65
Revises: a21cac6abfce
Create Date: 2025-08-07 13:44:32.765619

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "660b06b9ef65"
down_revision = "a21cac6abfce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "is_approved")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("is_approved", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
