"""create favourite complex model

Revision ID: 6f7bd1e06095
Revises: 22355b49b311
Create Date: 2025-08-01 21:09:08.671966

"""

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = "6f7bd1e06095"
down_revision = "22355b49b311"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourite_complexes",
        sa.Column(
            "complex_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["complex_id"],
            ["complexes.id"],
            name=op.f("fk_favourite_complexes_complex_id_complexes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_favourite_complexes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favourite_complexes")),
        sa.UniqueConstraint("user_id", "complex_id", name="uq_user_complex"),
    )
    op.create_unique_constraint(
        "uq_user_announcement",
        "favourite_announcements",
        ["user_id", "announcement_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_announcement", "favourite_announcements", type_="unique"
    )
    op.drop_table("favourite_complexes")
    # ### end Alembic commands ###
