"""change user_id type for blacklist

Revision ID: 90bde85bcc5a
Revises: c8bfc993ce57
Create Date: 2025-07-02 17:24:21.354455

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90bde85bcc5a"
down_revision = "c8bfc993ce57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blacklist", "user_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint(
        op.f("fk_blacklist_user_id_users"), "blacklist", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_blacklist_user_id_users"), "blacklist", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_blacklist_user_id_users"), "blacklist", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_blacklist_user_id_users"),
        "blacklist",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("blacklist", "user_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
