"""add on delete rule for blacklist user_id field

Revision ID: a21cac6abfce
Revises: 6f7bd1e06095
Create Date: 2025-08-05 16:28:07.465255

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "a21cac6abfce"
down_revision = "6f7bd1e06095"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_blacklist_user_id_users"), "blacklist", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_blacklist_user_id_users"),
        "blacklist",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_blacklist_user_id_users"), "blacklist", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_blacklist_user_id_users"), "blacklist", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
