"""Add unique constraint on complex_id and order

Revision ID: a55d64db48e1
Revises: a94066a57ee3
Create Date: 2025-06-22 14:39:02.979543

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "a55d64db48e1"
down_revision = "a94066a57ee3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_complex_order", "complexes_gallery", ["complex_id", "order"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_complex_order", "complexes_gallery", type_="unique")
    # ### end Alembic commands ###
