"""add order to gallery images

Revision ID: a94066a57ee3
Revises: 0780a5a36f6c
Create Date: 2025-06-22 13:12:57.723692

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a94066a57ee3"
down_revision = "0780a5a36f6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complexes_gallery", sa.Column("order", sa.SmallInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complexes_gallery", "order")
    # ### end Alembic commands ###
