"""change precision for apartment

Revision ID: d68322991b1a
Revises: 74d5be4c46bf
Create Date: 2025-07-29 15:30:20.340622

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d68322991b1a"
down_revision = "74d5be4c46bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartments",
        "area",
        existing_type=sa.NUMERIC(precision=4, scale=1),
        type_=sa.Numeric(precision=10, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartments",
        "area",
        existing_type=sa.Numeric(precision=10, scale=1),
        type_=sa.NUMERIC(precision=4, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
